"""add global_messages table

Revision ID: 37363f9c7131
Revises: b73ad13de174
Create Date: 2026-09-14 02:15:46.160286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37363f9c7131'
down_revision: Union[str, Sequence[str], None] = 'b73ad13de174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_messages_created_at'), 'global_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_messages_id'), 'global_messages', ['id'], unique=False)
    op.create_index(op.f('ix_global_messages_sender_id'), 'global_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_messages_sender_id'), table_name='global_messages')
    op.drop_index(op.f('ix_global_messages_id'), table_name='global_messages')
    op.drop_index(op.f('ix_global_messages_created_at'), table_name='global_messages')
    op.drop_table('global_messages')
    # ### end Alembic commands ###
